pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('sikasi')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    
    stages {

        stage('Login'){
            steps{
                //withCredentials([usernamePassword(credentialsId: 'mle-template', passwordVariable: 'DOCKER_REGISTRY_PWD', usernameVariable: 'DOCKER_REGISTRY_USER')]){
                //bat 'chcp 65001 && echo %DOCKER_REGISTRY_PWD% | docker login -u %DOCKER_REGISTRY_USER% --password-stdin'}
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
//                 sh 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }

        stage('Pull image'){
            steps{
                sh '''
                    docker pull stpic270/bd-secl-d:latest
                    docker pull stpic270/bd-secl-cassandra:latest
                    docker network create sec_lab
                    docker volume create sec_lab
                '''
            }
        }

        stage('Run container'){
            steps{
                sh  """ 
                    docker run --name cassandra -e JAVA_OPTS="-Xmx1024m -Xms1024m" --network sec_lab -v sec_lab:/config -d -p 9042:9042 stpic270/bd-secl-cassandra
                    docker run --name model -v sec_lab:/app/test --network sec_lab -d stpic270/bd-secl-d
                    docker exec cassandra bash -c "echo '\n' >> config/cassandra_config.txt && ip -4 -o address >> config/cassandra_config.txt"
                    docker exec model bash -c "scripts/cassandra.sh"
                    """
            }
        }

        stage('Checkout container logs') {
            steps {
                        sh  '''
                            docker logs --tail 30 model
                            '''
                    }
                }
       
	

    stage('Post always'){
            steps{
                dir("Big_data_second_lab") {
                    sh 'docker stop cassandra model'
                    sh 'docker logout'
                }
            }
        }
    }
}
